function [bound, singles, params] = create_molecules(ab, recep)

% CREATE_MOLECULES	Creates molecules and parameters for each binding pair.
%
%	Creates the receptor combinations for a given set of binding
%   information output from the create_binding() function.
%
%	USAGE:
%		[BOUND, SINGLES, PARAMS] = CREATE_MOLECULES(AB, RECEP)
%
%	INPUT:
%		AB = a string vector with the antibodies to use in the complexes
%
%       RECEP = a cell array of string vectors with the receptor(s) to use
%       in the complexes; the rows of the array should correspond to the
%       antibodies in AB
%
%	OUTPUT:
%       BOUND = antibody-receptor combinations corresponding to
%       molecules in the m structure; e.g., only includes BS1_6R_8R and not
%       BS1_8R_6R because they are the same molecule
%
%       SINGLES = all of the individual antibodies and receptors that
%       contribute to the bound complexes in BOUND
%
%       PARAMS = all of the antibody-receptor combinations corresponding
%       to parameters in the p structure; e.g., does include both BS1_6R_8R
%       and BS1_8R_6R because they are separate have separate rate
%       constants
%
%	NOTES:
%       This function is designed to take the output of CREATE_BINDING and
%       generate the specific molecules and binding parameters from it. To
%       generate the different binding combinations and stoichiometry,
%		use CREATE_BINDING.
%
%       To generate the m and p structures for the model, use the
%       CREATE_PARAMS function.
%
%	See also CREATE_BINDING, CREATE_PARAMS, PASTE.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Argument Validation

arguments
    ab string
    recep {mustBeA(recep, ["string", "cell"])}
end

% Validate that the antibodies and receptors are the same length and
% convert the receptors to a cell array for correct indexing
[ab, recep] = validate_ab(ab, recep);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Create Receptor Combinations

% ---------- BINDING INTERACTIONS ----------
% Generate the binding interactions from the antibodies and receptors
binding = create_binding(ab, recep);

% ---------- PARAMETERS ----------
% Parameters are generated by combining together the input molecules
params = paste(binding);

% ---------- BOUND COMPLEXES ----------
% Bound molecules are generated splitting the parameters and sorting the
% receptors in order, then removing any extra molecules

% Initialize output array
bound = strings(size(params));

for i = 1:length(bound)

    % Split the parameters into components
    ab = regexprep(params(i), "_[0-9]R.*$", ""); % Strip receptors
    recep = regexprep(params(i), "^.*?([0-9]R.*)$", "$1"); % Strip ab
    % ? makes the matching lazy - matches as few characters as possible

    % Sort receptors in order and rejoin antibodies and receptors
    recep = sort(strsplit(recep, "_"));
    bound(i) = paste([ab, recep]);
end

% Remove duplicate molecules
bound = unique(bound, 'stable');

% ---------- SINGLE MOLECULES ----------
% Individual molecules are determined by finding all complexes that do not
% end in a receptor
% Matches all complexes that end in a receptor
pattern = "_[0-9]R$";

% Find all matches and select non-matching complexes
idx = regexpl(binding(:,1), pattern);
singles = unique(binding(~idx,1), 'stable');

% Find all individual receptors and prepend "IL"
receptors = unique(binding(:,2), 'stable');
receptors = append("IL", receptors);

% Concatenate receptors onto input list
singles = [singles; receptors];
