function id = setup_id(yin, params)

% SETUP_ID	Generate simulation ID table to link input variables.
%
%	Combines the initial concentration ID values and the parameter ID
%	values into a single table with a unique simulation ID for each pair.
%	The output table is used to connect which initial concentrations and
%	parameter values were used for each simulation.
%
%	USAGE:
%		ID = SETUP_ID(YIN, PARAMS)
%
%	INPUT:
%		YIN = table with columns for the simulation ID, time period type,
%		starting and ending times for the time period, species name, and
%		initial concentration for that species for each time period;
%		generated by SETUP_INPUT
%
%       P = table with columns for the simulation ID, parameter name, and
%		parameter value for each parameter in the simulation; generated by
%       SETUP_INPUT
%
%	OUTPUT:
%       ID = table with columns for the simulation ID, initial
%       concentration ID, and parameter value ID; used for connecting the
%       initial concentrations used for the simulation with the parameter
%       values used; used as input to BINDING_SIM
%
%	NOTES:
%		Passing in a table with which initial concentration ID values and
%		which parameter ID values are used for each simulation is much
%		smaller and easier than combining all of the input variables into a
%		single table. This is helpful when running a large number of
%		simulations.
%
%	See also BINDING_SIM, SETUP_INPUT, SPLIT_OBJECT, COMBINE.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Argument Validation

arguments
    yin table
    params table
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Create a Combined ID Table

% Get unique ID values from input tables
ConcID = unique(yin.ConcID);
ParamID = unique(params.ParamID);

% Combine ID values into a separate table
id = combine(ConcID, ParamID);

% Add a column for the input ID number
id = addvars(id, (1:height(id))', 'Before', 1, 'NewVariableNames', "ID");

end
